### ISSUE TITLE
Error "Transaction failed" 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/tech-dapp#174]
Address : 0xb760FE1bbC4A2752aBCBb28291a57Cb0cA99fF44

This is what happens : 

1. Tx sent and this screen last for about 10 minutes.
![Screen Shot 2021-02-15 at 12.04.22 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/f4bb1bbb-455e-4ee8-b569-8c0df8c816e2)

2. Tx failed screen eventually shows. 
![Screen Shot 2021-02-15 at 12.12.53 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/4be2cc23-f729-4d30-a148-00529838ba66)

3. She was on Eth Mainnet for the above transaction. I had her switch to xdai and she received this message after that change. We x'd out of this. 
![Screen Shot 2021-02-15 at 12.13.02 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/406e0e2e-4ae6-4c77-8eb8-1c5154432477)

4. The above happened while I am on a call with her. She just checked again and is now seeing the infamous NAN error. 
![photo_2021-02-15_12-22-39.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/56340ab5-729a-47c2-8cfe-c1da3c86b351)

**Comment by GriffGreen** [comment]
The Real cause here is that she didnt know that her first tx was pending.... the gas prices probably went up on her...

Then she made a second tx and that one failed AFTER the first one succeeded.... it failed cause she didnt have a second 450 to send us...

Probably a good thing! 

ACTION: We should change the text on the DApp to be more explicit. 

Instead of: 

![Screen Shot 2021-02-15 at 8.20.42 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8336d109-5398-463b-9134-b5f5bd276990)

Please be patient while the Ethereum miners to add your transaction to the blockchain. If there is an issue please reach out us on telegram: https://t.me/CSTKSwissMembershipDApp

**Comment by mendesfabio** [comment]
![image](https://user-images.githubusercontent.com/43360747/107976378-35027e00-6f98-11eb-9b48-ec532ee02e65.png)

@GriffGreen updated!
