### ISSUE TITLE
Change the "transaction failed" wording on this screen

### ISSUE THREAD

**Issue by Santigs** [commons-stack/tech-dapp#181]
I have been trying to finish my application and run into two issues.
First, I was not aware there are two transactions needed. I believe it is worth mentioning it to the user.
After the first one went through (it took a while as I set fees quite low) I did launch the donation one to giveth bridge.
Again I entered a low fee and the transaction is still pending in ethscan but the application showed an error message after a while.

![Screenshot 2021-02-20 at 12 37 23](https://user-images.githubusercontent.com/34634436/108594226-f0505b80-7378-11eb-9f87-c589948d77bf.png)

You can see the transaction is still pending in the explorer, I will wait to see if it finally goes through

![Screenshot 2021-02-20 at 12 41 59](https://user-images.githubusercontent.com/34634436/108594246-170e9200-7379-11eb-9626-b810d588f3cf.png)

**Comment by tamarandom** [comment]
The membership dues tx went through this morning. Yay. But...

This error message is misleading. The transaction did not fail so we will want to rephrase it for greater clarity. 

Is it correct to assume that this error is thrown due to a timeout? How long is the timeout? 

Perhaps something like this. Maybe less wordy?

"Something has gone wrong! Please check the transaction status in your Metamask. If it is still pending, it may be some time before the transaction is completed. This is most likely due to the gas setting used being lower than the average current gas price. You will receive an email from the Swiss Association when the transaction clears. If you have any questions please contact xxx."

**Comment by tamarandom** [comment]
Is this short enough? 

"Something went wrong! Check your transaction in Metamask. A pending transaction is often due to gas fee that is much lower than the current rates. When the transaction is completed, the Swiss Association will send you a confirmation email. If you have any questions please contact xxx."

**Comment by tamarandom** [comment]
Closing. Reopened by mistake. ;(
